const { contextBridge, ipcRenderer } = require('electron');

const call = (ch) => (...args) => ipcRenderer.invoke(ch, ...args);

contextBridge.exposeInMainWorld('api', {
  licenseState: call('licenseState'),
  activateLicense: call('activateLicense'),
  getAll: call('getAll'),
  addWorker: call('addWorker'),
  addProject: call('addProject'),
  addLog: call('addLog'),
  addPayment: call('addPayment'),
  updateWorker: call('updateWorker'),
  updateProject: call('updateProject'),
  updateLog: call('updateLog'),
  updatePayment: call('updatePayment'),
  deleteWorker: call('deleteWorker'),
  deleteProject: call('deleteProject'),
  deleteLog: call('deleteLog'),
  deletePayment: call('deletePayment'),
  addProjectPayment: call('addProjectPayment'),
  updateProjectPayment: call('updateProjectPayment'),
  deleteProjectPayment: call('deleteProjectPayment'),
  addExpense: call('addExpense'),
  updateExpense: call('updateExpense'),
  deleteExpense: call('deleteExpense'),
  pickPhoto: call('pickPhoto'),
  photoUrl: call('photoUrl'),
  openPhoto: call('openPhoto'),
  resetAll: call('resetAll'),
  importAll: call('importAll'),
  exportBackup: call('exportBackup'),
  importBackup: call('importBackup'),
  authState: call('authState'),
  setupAdmin: call('setupAdmin'),
  login: call('login'),
  listUsers: call('listUsers'),
  addUser: call('addUser'),
  updateUser: call('updateUser'),
  deleteUser: call('deleteUser'),
  getBackupSettings: call('getBackupSettings'),
  setBackupSettings: call('setBackupSettings'),
  pickBackupDir: call('pickBackupDir'),
  backupNow: call('backupNow'),
  listBackups: call('listBackups'),
  restoreBackupFile: call('restoreBackupFile')
});
